apiVersion: v2
name: netbird-coredns
description: A Helm chart for NetBird CoreDNS - DNS server with custom DNS records management via HTTP API
type: application
version: 0.1.0
appVersion: 0.1.3
home: https://github.com/christian-deleon/netbird-coredns
maintainers:
  - name: Christian De Leon
keywords:
  - dns
  - coredns
  - netbird
