{{- if and .Values.config.setupKey .Values.config.setupKey.value (not .Values.config.setupKey.secret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird-coredns.fullname" . }}-setup-key
  labels:
    {{- include "netbird-coredns.labels" . | nindent 4 }}
type: Opaque
data:
  setup-key: {{ .Values.config.setupKey.value | b64enc }}
{{- end }}
